name: patient_app
description: "Production Level POS System"
version: 2.0.0+12
publish_to: 'none'

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
    flutter_localizations:
    sdk: flutter
  
  # State Management & DI
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^13.1.0
  
  # API & Serialization
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Database (Offline-first)
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Security & Storage
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  
  # UI & Responsive
  flutter_screenutil: ^5.9.0
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Utils
  intl: ^0.20.2
  logger: ^2.0.2
  fluttertoast: ^8.2.10
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
